// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250804151201_AddedSeedingDataToDiaryEntry")]
    partial class AddedSeedingDataToDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Went to eat choma.",
                            Created = new DateTime(2025, 8, 4, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Eating"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Went to sleep at 10pm.",
                            Created = new DateTime(2025, 8, 4, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sleeping"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Woke up at 6am.",
                            Created = new DateTime(2025, 8, 4, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Waking up"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
